# Generated by Django 3.2 on 2025-04-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=6, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('married', 'Женат/Замужем'), ('in_relationship', 'В отношениях'), ('searching', 'В поиске')], max_length=16, null=True, verbose_name='Семейное положение'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на ВКонтакте'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp'),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на YouTube'),
        ),
    ]
