# Generated by Django 3.2 on 2025-04-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_confirmationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
