# Generated by Django 3.2 on 2025-04-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
