# Generated by Django 3.2 on 2025-04-06 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20250402_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^[-a-zA-Z0-9_]+$')], verbose_name='Относительная ссылка'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^[-a-zA-Z0-9_]+$')], verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^[-a-zA-Z0-9_]+$')], verbose_name='Относительная ссылка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^[-a-zA-Z0-9_]+$')], verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='title',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^[-a-zA-Z0-9_]+$')], verbose_name='Ссылка'),
        ),
    ]
