# Generated by Django 3.2 on 2025-04-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20250407_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, max_length=1800, null=True),
        ),
    ]
