# Generated by Django 3.2 on 2025-04-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='title',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
